[accessLog]
[api]
    dashboard = true
    insecure = true
[logs]
    level = 'ERROR'
[entryPoints]
[entryPoints.web]
    address = ":80"
    [entryPoints.web.http]
    [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"
        permanent = true

[entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]
        certResolver = "default"
[entryPoints.wss]
    address = ":8001"


[providers]
    [providers.docker]
        watch = true
        exposedByDefault = false
        network = "web"

[certificatesResolvers]
    [certificatesResolvers.default]
        [certificatesResolvers.default.acme]
            email = "contact@queel.io"
            storage = "acme.json"
            caServer = "https://acme-v01.api.letsencrypt.org/directory"
            [certificatesResolvers.default.acme.tlsChallenge]

