FROM node:16.13.2
#RUN apt-get update
#RUN apt-get install -y make build-essential libssl-dev zlib1g-dev
#RUN apt-get install -y libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm
#RUN apt-get install -y libncurses5-dev  libncursesw5-dev xz-utils tk-dev
#RUN wget https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tgz
#RUN tar xvf Python-3.6.4.tgz && cd Python-3.6.4 && ./configure && make -j8 && make altinstall
#RUN apt-get install libc6 musl -y
RUN npm install pm2 -g


